name       : ruby-trollop
version    : 2.1.3
release    : 3
source     :
    - https://rubygems.org/downloads/trollop-2.1.3.gem : 980390db9d5a095cb49b53773360d841d3e52f23faafb57543055fa6664efde7
license    : MIT
component  : programming.ruby
summary    : Trollop is a commandline option parser for Ruby that just gets out of
    your way.
description: |
    Trollop is a commandline option parser for Ruby that just gets out of your way. One line of code per option is all you need to write. For that, you get a nice automatically-generated help page, robust option parsing, command subcompletion, and sensible defaults for everything you don't specify.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
